version: '3.5'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        container_name: postgres
        # volumes:
        #     - ./pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - postgres-db-network
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: idp-server
        env_file:
            - .env
        ports:
            - '${PORT}:${PORT}'
        depends_on:
            - db
        networks:
            - postgres-db-network
        volumes:
            - ./src:/app/src
networks:
    postgres-db-network:
        driver: bridge
