name: idp-api

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 22
      - run: npm ci
      - run: npm run test
      - run: npm run build
  deploy:
    if: github.ref == 'refs/heads/main'
    env:
      deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
    run: |
      curl "$deploy_url"
        